path: attrs/line/category/de
content:
    en:
        title: Line Categories in Germany
        body: |
            Over the years, several categories for railways have been
            established in Germany. In the early days, railways were a matter
            regulated by the various German states and as such regulation
            differed somewhat. However, the basic categories have been quite
            similar. After the German unification of 1871, this regulation
            was step by
            step moved to imperial and later federal level.

            Regular railways are now being operated under the
            _Eisenbahn-Bau-und Betriebsordnung_ (or EBO, earlier abbreviated
            as BO), a federal
            regulation. They are categorized either as primary or secondary
            railways, _Hauptbahn_ or _Nebenbahn_ in German. The regulation
            puts higher requirements on primary railway but in turn also
            allows higher speeds.

            The fact that the rules are different for operation entirely within
            the limits of a station -- mostly allowing for shunting, has lead
            to the categorization of some lines with very limited freight
            service as being part of a station. This would be termed as
            _Bahnhofsgleis_ or station track in German.

            Before World War II, some states had a third category of tertiary
            railways. These were regulated by state law and had been
            established to encourage railways being build in rural areas by
            relaxing requirements. Prussia was very successful in this, where
            there were lots of these railways, named _Kleinbahn_ there. Other
            names where used in different states such as _Lokalbahn_. After
            1945,
            most of these railways were closed down following widespread
            motorization and most states abandoned this category, putting the
            remaining railways under secondary railway regulation. The only
            exception is the state of Berlin where there this category exists
            still.

            Narrow gauge railways have their own regulatory regime, the federal
            _Eisenbahn-Bau- und Betriebsordnung für Schmalspurbahnen_. Because
            the regulation is in large parts identical to that for regular
            secondary railways we classify these as _Nebenbahn_ within the
            project. In the past, many narrow gauge railways have been operated
            as tertiary railways. These receive the _Kleinbahn_ category.

            Trams, again, have their own regime. The regulation is called
            _Verordnung über den Bau und Betrieb der Straßenbahnen_ and is
            abbreviated as BOStrab. On occasion, regular railways have been
            re-designated as trams to benefit from the far more relaxed
            requirements for trams thus allowing cheaper operation of the line.

            Finally, there are some railways that have not been licensed for
            public transportation. These are usually industrial railways such
            as the railways of mining corporations and short tracks leading to
            factories. These again have their own regulation laid out by the
            states and are either called _Verordnung über den Bau und Betrieb
            von Anschlussbahnen_ (BOA) or _Eisenbahn-Bau- und Betriebsordnung
            für Anschlussbahnen_ (EBOA). Within the project we use the term
            Anschlussbahn. 

---
path: attrs/line/category/de.Hauptbahn
content:
    en:
        title: Primary Railway in Germany
        body: |
            Primary railway lines are called _Hauptbahn_ in Germany. They
            are marked by stricter requirements for construction and operation
            allowing for higher speeds and frequencies of trains. 

---
path: attrs/line/category/de.Nebenbahn
content:
    en:
        title: Secondary Railway in Germany
        body: |
            Secondary railway lines are called _Nebenbahn_ in Germany. They
            are marked by more relaxed requirements for construction and
            operation allowing for cheaper constructions and operations. 

---
path: attrs/line/category/de.Kleinbahn
content:
    en:
        title: Tertiary Railway in Germany
        body: |
            After the main railway network was established during the second
            half of the 19th century, there were still large areas that had no
            railway line. These were mostly sparsely populated areas with low
            demand where it was near impossibly to profitably run a railway
            operation. In order to boost development of these areas, many
            German states implemented the category of tertiary railways with
            very relaxed requirements on construction and operation in order to
            improve the economics for railways in such areas. This was
            especially fruitful in the state of Prussia, which had many of
            these areas after introduction of what became known as Kleinbahn,
            literally petty railway, a wide network of such railways was
            developed by communities, counties and private entrepreneurs. In
            other states, these railways had different names: Provinzialbahn,
            Lokalbahn, etc.

            After World War II, with the spread of the auto-mobile, many of
            these railways have lost their purpose and have been closed down.
            In East Germany, they have been nationalised and merged into the
            state railway. In West Germany, most states have since abandoned
            the category. The few lines that are left are now operated as
            secondary railways. The only exception is the state of Berlin,
            where the category still exists.

---
path: attrs/line/category/de.Bfgleis
content:
    en:
        title: Station Tracks in Germany
        body: |
            Regulation for the operation of railways usually distinguishes
            between operation within and outside of stations. The main
            difference usually is that inside of stations shunting is allowed,
            which is the movement of vehicles at low speed without strict
            measures of protection from collisions. In other words, within the
            station limits, movement of vehicles can be done without expensive
            technical equipment.

            During the demise of the railway, many lines have lost passenger
            services and have only been kept open to allow freight traffic to
            some factories along the line. Often this meant one service a day
            or even a week. In some cases, these services have been simplified
            by including the railway line into the limits of a station. The
            German terms for this are _Bahnhofsgleis_ (station track) or
            _Streckenrangiergleis_ (lit. railway line shunting track). 

---
path: attrs/line/category/de.Strab
content:
    en:
        title: Tram in Germany
        body: |
            Trams are governed by a separate regulation, the
            _Verordnung über den Bau und Betrieb der Straßenbahnen_
            (Regulation of construction and operation of tramways), mainly
            because of the different for rail vehicles operating in a
            shared environment with road vehicles.

            Besides actual tram lines, this category contains underground
            lines, monorails, and similar railways but not mountain railways,
            cable cars, funiculars and such. Tram lines do not exclusively
            exist in cities. Some networks in rural areas have been put into
            this category to benefit from the easier operational regime. 

---
path: attrs/line/category/de.Anschl
content:
    en:
        title: Industrial Railway in Germany
        body: |
            Various railway lines or spurs have been built without the
            intention to for public service. They are usually owned by a
            industrial cooperation such as a mining company and are only used
            for internal transportation of freight and, in some cases,
            employees. Such railways are usually categorized under
            _Anschlussbahn_ (lit. connection railway), since most of them are a
            mere track connecting a factory yard with a nearby railway line.
            Despite that, there are wide networks of such railways, such as the
            railways of the open-pit coal mining operations. 
